# Site Info
title:              "howCatCanCode"
description:        "I write about all the stuff I’m doing related to Computer Science and Information Technology.
  Following this blog would help you grow. 
  It’ll add up many new resources for learning help you to understand Computer Science fundamentals.
  We discuss Ideas here. Let’s CODE."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "moghya" # Your name here
author_email:       sawantpshubham@gmail.com # Your email here
author_gravatar:    2e45452b15e5b372c25e9ac60ca0bd2c # Your Gravatar md5 hash here for logo
twitter_username:   moghya # Your Twitter username here
github_username:    moghya # Your GitHub username here

# Site Settings
baseurl:            "http://moghya.me/howCatCanCode" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
